<?php
require_once($_SERVER['DOCUMENT_ROOT'].'/includes/onlyadminallowed.php');
include('directorystructure.php');
if(isset($_GET["dir"]))
{
    dirStructure($_GET["dir"]);
}
else 
{
    dirStructure();
}
?>
